/// Built-in categories seeded on first launch and when missing on upgrade.
const defaultCategories = [
  'Food',
  'Groceries',
  'Shopping',
  'Fuel',
  'Travel',
  'Bills',
  'Utilities',
  'Entertainment',
  'Medical',
  'Education',
  'Investment',
  'Salary',
  'Rent',
  'EMI',
  'Insurance',
  'Tax',
  'Subscription',
  'Gifts',
  'Personal Care',
  'Miscellaneous',
];
